language: python
sudo: false

jobs:
  include:
    - stage: "travis-ci testing 3.7"
      os: linux
      python:
        - '3.7'
      install:
        - pip install -r requirements_dev.txt
      script:
        - "PYTHONPATH=. pytest -v -s --cov=pingping tests"
      after_success:
        - coveralls

      script: echo "Deployment Done..!"
