language: python
sudo: false
os:
  - linux

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - "PYTHONPATH=. pytest -v -s --cov=pingping tests"

after_success:
  - coveralls

